### ISSUE TITLE
Row filter support to DataSocket

### ISSUE THREAD

**Issue by Jupetus** [SneaksAndData/adapta#291] opened 2023-07-14 11:09 UTC
DataSocket class could also support parsing row filters as it seems like common operation to many repositories 

Example implementation that extends the Datasocket:
```
@dataclass(frozen=True)
class DataSocketContainer(DataSocket):
    """DataSocket Containing Container"""

    filters: Dict[str, Union[str, List[str]]] = field(default_factory=dict)

    def _construct_filters(self):
        """Turn filters dictionary into pyarrow expressions"""
        expressions = [
            pyarrow_field(column_name).isin(maybe_make_list(filter_values))
            for column_name, filter_values in self.filters.items()
            if not isinstance(filter_values, bool)
        ]
        constraints = [
            pyarrow_field(column_name) if filter_values else ~pyarrow_field(column_name)
            for column_name, filter_values in self.filters.items()
            if isinstance(filter_values, bool)
        ]
        #TODO: Missing comparison field(s)
        return expressions + constraints

    def get_socket_filters(self) -> Expression:
        """Returns the filters for the socket"""
        return reduce(lambda x, y: x & y, self._construct_filters(), scalar(True))

```

**Comment by george-zubrienko** [comment] 2023-07-22 17:54
@Jupetus `DataSocket` is a model class, not a functionality class. Closing as duplicate of #201

**Closed by george-zubrienko** 2023-07-22 17:54 UTC
Labels: code/new-feature
